# Praktikum 5 - Naive Bayes dengan Preprocessing dan K-Cross Validation

# Naive Bayes Classifier

In [1]:
import numpy as np
import pandas as pd
from IPython import display

## Data

In [2]:
df = pd.read_csv("restaurant.csv")

In [3]:
df.head()

Alternate    Bar Fri/Sat Hungry Patrons Price   Rain     Res      Type  \
0       Yes     No      No    Yes    Some   $$$     No     Yes    French   
1       Yes     No      No    Yes    Full     $     No      No      Thai   
2        No    Yes      No     No    Some     $     No      No    Burger   
3       Yes     No     Yes    Yes    Full     $     No      No      Thai   
4       Yes     No     Yes     No    Full   $$$     No     Yes    French   

         Est WillWait  
0       0-10      Yes  
1      30-60       No  
2       0-10      Yes  
3      10-30      Yes  
4        >60      No

In [4]:
df

Alternate    Bar Fri/Sat Hungry Patrons Price    Rain     Res      Type  \
0        Yes     No      No    Yes    Some   $$$      No     Yes    French   
1        Yes     No      No    Yes    Full     $      No      No      Thai   
2         No    Yes      No     No    Some     $      No      No    Burger   
3        Yes     No     Yes    Yes    Full     $      No      No      Thai   
4        Yes     No     Yes     No    Full   $$$      No     Yes    French   
5         No    Yes      No    Yes    Some    $$     Yes     Yes   Italian   
6         No    Yes      No     No    None     $     Yes      No    Burger   
7         No     No      No    Yes    Some    $$     Yes     Yes      Thai   
8         No    Yes     Yes     No    Full     $     Yes      No    Burger   
9        Yes    Yes     Yes    Yes    Full   $$$      No     Yes   Italian   
10        No     No      No     No    None     $      No      No      Thai   
11       Yes    Yes     Yes    Yes    Full     $      No      No    Burger   

          Est WillWait  
0        0-10      Yes  
1       30-60       No  
2        0-10      Yes  
3       10-30      Yes  
4         >60      No   
5        0-10      Yes  
6        0-10       No  
7        0-10      Yes  
8         >60      No   
9       10-30      No   
10       0-10      No   
11      30-60      Yes

In [5]:
df['Alternate'].unique()

array(['Yes', 'No'], dtype=object)

In [6]:
df['Bar'].unique()

array([' No', '  Yes', '  No', ' Yes'], dtype=object)

In [7]:
df['Bar']=df['Bar'].replace(to_replace =[" No", "  No"], 
                            value ="No")
df['Bar']=df['Bar'].replace(to_replace =[" Yes", "  Yes"], 
                            value ="Yes")

In [8]:
df['Bar'].unique()

array(['No', 'Yes'], dtype=object)

In [9]:
df['Fri/Sat'].unique()

array(['  No', ' No', '  Yes', ' Yes'], dtype=object)

In [10]:
df['Fri/Sat']=df['Fri/Sat'].replace(to_replace =[" No", "  No"], 
                            value ="No")
df['Fri/Sat']=df['Fri/Sat'].replace(to_replace =[" Yes", "  Yes"], 
                            value ="Yes")

In [11]:
df['Fri/Sat'].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
df['Hungry'].unique()

array(['  Yes', '  No', ' Yes', ' No'], dtype=object)

In [13]:
df['Hungry']=df['Hungry'].replace(to_replace =[" No", "  No"], 
                            value ="No")
df['Hungry']=df['Hungry'].replace(to_replace =[" Yes", "  Yes"], 
                            value ="Yes")

In [14]:
df['Hungry'].unique()

array(['Yes', 'No'], dtype=object)

In [15]:
df['Patrons'].unique()

array([' Some', ' Full', '  Some', '  Full', '  None'], dtype=object)

In [16]:
df['Patrons']=df['Patrons'].replace(to_replace=[' Some','  Some'],value='Some')
df['Patrons']=df['Patrons'].replace(to_replace=[' Full','  Full'],value='Full')
df['Patrons']=df['Patrons'].replace(to_replace=['  None'],value='None')

In [17]:
df['Patrons'].unique()

array(['Some', 'Full', 'None'], dtype=object)

In [18]:
df['Price'].unique()

array([' $$$', ' $', ' $$'], dtype=object)

In [19]:
df['Price']=df['Price'].replace(to_replace=[' $$$'],value='$$$')
df['Price']=df['Price'].replace(to_replace=[' $'],value='$')
df['Price']=df['Price'].replace(to_replace=[' $$'],value='$$')

In [20]:
df['Rain'].unique()

array([' No', '   No', '  Yes', '   Yes'], dtype=object)

In [21]:
df['Rain']=df['Rain'].replace(to_replace =["  No", '   No',' No'], 
                            value ="No")
df['Rain']=df['Rain'].replace(to_replace =['   Yes', "  Yes"], 
                            value ="Yes")

In [22]:
df['Rain'].unique()

array(['No', 'Yes'], dtype=object)

In [23]:
df.columns

Index(['Alternate', 'Bar', 'Fri/Sat', 'Hungry', 'Patrons', 'Price', 'Rain',
       'Res', 'Type', 'Est', 'WillWait'],
      dtype='object')

In [24]:
df['Res'].unique()

array(['   Yes', '   No', '  Yes', '  No'], dtype=object)

In [25]:
df['Res']=df['Res'].replace(to_replace =["  No", '   No'], 
                            value ="No")
df['Res']=df['Res'].replace(to_replace =['   Yes', "  Yes"], 
                            value ="Yes")

In [26]:
df['Res'].unique()

array(['Yes', 'No'], dtype=object)

In [27]:
df['Type'].unique()

array([' French', '  Thai', '  Burger', ' Italian', ' Thai'], dtype=object)

In [28]:
df['Type']=df['Type'].replace(to_replace=[' French'],value='French')
df['Type']=df['Type'].replace(to_replace=['  Thai',' Thai'],value='Thai')
df['Type']=df['Type'].replace(to_replace=['  Burger'],value='Burger')
df['Type']=df['Type'].replace(to_replace=[' Italian'],value='Italian')

In [29]:
df['Est'].unique()

array(['  0-10', '    30-60', '    10-30', '  >60', ' 0-10', '    0-10',
       ' 10-30', '  30-60'], dtype=object)

In [30]:
df['Est']=df['Est'].replace(to_replace=['  0-10',' 0-10','    0-10',],value='0-10')
df['Est']=df['Est'].replace(to_replace=['    30-60','  30-60'],value='30-60')
df['Est']=df['Est'].replace(to_replace=['    10-30',' 10-30'],value='10-30')
df['Est']=df['Est'].replace(to_replace=['  >60'],value='>60')

In [31]:
df['Est'].unique()

array(['0-10', '30-60', '10-30', '>60'], dtype=object)

In [32]:
df.columns

Index(['Alternate', 'Bar', 'Fri/Sat', 'Hungry', 'Patrons', 'Price', 'Rain',
       'Res', 'Type', 'Est', 'WillWait'],
      dtype='object')

In [33]:
df['WillWait'].unique()

array(['   Yes', '  No', '  Yes', '    No ', '   No', '  No ', '   No '],
      dtype=object)

In [34]:
df['WillWait']=df['WillWait'].replace(to_replace=['   Yes','  Yes'],value='Yes')
df['WillWait']=df['WillWait'].replace(to_replace=['  No','    No ','   No','  No ','   No '],value='No')

In [35]:
df['WillWait'].unique()

array(['Yes', 'No'], dtype=object)

In [36]:
X = df.drop('WillWait',axis=1)
y = df['WillWait']

## Preprocessing

### One-Hot Encoding

In [37]:
X_enc=pd.get_dummies(X)

In [38]:
X_enc.columns

Index(['Alternate_No', 'Alternate_Yes', 'Bar_No', 'Bar_Yes', 'Fri/Sat_No',
       'Fri/Sat_Yes', 'Hungry_No', 'Hungry_Yes', 'Patrons_Full',
       'Patrons_None', 'Patrons_Some', 'Price_$', 'Price_$$', 'Price_$$$',
       'Rain_No', 'Rain_Yes', 'Res_No', 'Res_Yes', 'Type_Burger',
       'Type_French', 'Type_Italian', 'Type_Thai', 'Est_0-10', 'Est_10-30',
       'Est_30-60', 'Est_>60'],
      dtype='object')

In [39]:
X_enc=X_enc.drop(['Alternate_No','Bar_No','Fri/Sat_No','Hungry_No','Patrons_Full','Price_$','Rain_No','Res_No','Type_Burger','Est_0-10'],axis=1)

In [40]:
X_enc.columns

Index(['Alternate_Yes', 'Bar_Yes', 'Fri/Sat_Yes', 'Hungry_Yes', 'Patrons_None',
       'Patrons_Some', 'Price_$$', 'Price_$$$', 'Rain_Yes', 'Res_Yes',
       'Type_French', 'Type_Italian', 'Type_Thai', 'Est_10-30', 'Est_30-60',
       'Est_>60'],
      dtype='object')

In [41]:
X=X_enc

In [42]:
X

Alternate_Yes  Bar_Yes  Fri/Sat_Yes  Hungry_Yes  Patrons_None  \
0               1        0            0           1             0   
1               1        0            0           1             0   
2               0        1            0           0             0   
3               1        0            1           1             0   
4               1        0            1           0             0   
5               0        1            0           1             0   
6               0        1            0           0             1   
7               0        0            0           1             0   
8               0        1            1           0             0   
9               1        1            1           1             0   
10              0        0            0           0             1   
11              1        1            1           1             0   

    Patrons_Some  Price_$$  Price_$$$  Rain_Yes  Res_Yes  Type_French  \
0              1         0          1         0        1            1   
1              0         0          0         0        0            0   
2              1         0          0         0        0            0   
3              0         0          0         0        0            0   
4              0         0          1         0        1            1   
5              1         1          0         1        1            0   
6              0         0          0         1        0            0   
7              1         1          0         1        1            0   
8              0         0          0         1        0            0   
9              0         0          1         0        1            0   
10             0         0          0         0        0            0   
11             0         0          0         0        0            0   

    Type_Italian  Type_Thai  Est_10-30  Est_30-60  Est_>60  
0              0          0          0          0        0  
1              0          1          0          1        0  
2              0          0          0          0        0  
3              0          1          1          0        0  
4              0          0          0          0        1  
5              1          0          0          0        0  
6              0          0          0          0        0  
7              0          1          0          0        0  
8              0          0          0          0        1  
9              1          0          1          0        0  
10             0          1          0          0        0  
11             0          0          0          1        0

### Feature Selection

### Feature Selection : by Variance Threshold

<a><img src="https://cdn1.byjus.com/wp-content/uploads/2021/03/variance-and-sd-formula.png"/></a>

<a><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNy_TQDpkMzCmytuj1Ncr_GcYLu7pZkpH2cw&usqp=CAU"></a>

In [43]:
X_example = [[0, 2, 0, 3], [0, 1, 4, 3], [0, 1, 1, 3]]

In [44]:
np.array(X_example)

array([[0, 2, 0, 3],
       [0, 1, 4, 3],
       [0, 1, 1, 3]])

In [45]:
from sklearn.feature_selection import VarianceThreshold

In [46]:
selector = VarianceThreshold()

In [47]:
selector.fit_transform(X_example)

array([[2, 0],
       [1, 4],
       [1, 1]])

In [48]:
XVarianceThreshold = selector.fit_transform(X)

In [49]:
XVarianceThreshold.shape

(12, 16)

### Feature Selection : by Mutual Infomation/Information Gain

<a><img src="https://miro.medium.com/max/1400/1*sHASwCjxy-Tsr3eaDTeHXw.png"></a>

In [50]:
from sklearn.feature_selection import mutual_info_classif

In [51]:
XMutualInformationValue = mutual_info_classif(X,y)

In [52]:
XMutualInformationValue

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.91901154e-01,
       0.00000000e+00, 5.47456710e-01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       6.31313131e-04, 0.00000000e+00, 0.00000000e+00, 1.67595599e-01])

In [53]:
XMutualInformation=X

In [54]:
XMutualInformation

Alternate_Yes  Bar_Yes  Fri/Sat_Yes  Hungry_Yes  Patrons_None  \
0               1        0            0           1             0   
1               1        0            0           1             0   
2               0        1            0           0             0   
3               1        0            1           1             0   
4               1        0            1           0             0   
5               0        1            0           1             0   
6               0        1            0           0             1   
7               0        0            0           1             0   
8               0        1            1           0             0   
9               1        1            1           1             0   
10              0        0            0           0             1   
11              1        1            1           1             0   

    Patrons_Some  Price_$$  Price_$$$  Rain_Yes  Res_Yes  Type_French  \
0              1         0          1         0        1            1   
1              0         0          0         0        0            0   
2              1         0          0         0        0            0   
3              0         0          0         0        0            0   
4              0         0          1         0        1            1   
5              1         1          0         1        1            0   
6              0         0          0         1        0            0   
7              1         1          0         1        1            0   
8              0         0          0         1        0            0   
9              0         0          1         0        1            0   
10             0         0          0         0        0            0   
11             0         0          0         0        0            0   

    Type_Italian  Type_Thai  Est_10-30  Est_30-60  Est_>60  
0              0          0          0          0        0  
1              0          1          0          1        0  
2              0          0          0          0        0  
3              0          1          1          0        0  
4              0          0          0          0        1  
5              1          0          0          0        0  
6              0          0          0          0        0  
7              0          1          0          0        0  
8              0          0          0          0        1  
9              1          0          1          0        0  
10             0          1          0          0        0  
11             0          0          0          1        0

In [55]:
XMutualInformation.loc[12]=XMutualInformationValue

In [56]:
XMutualInformation = XMutualInformation.drop([col for col in X.columns if X[col][12]==0], axis=1)


In [57]:
XMutualInformation = XMutualInformation.drop(12)

In [58]:
XMutualInformation = XMutualInformation.replace(to_replace=[0.0],value=0)
XMutualInformation = XMutualInformation.replace(to_replace=[1.0],value=1)

In [59]:
XMutualInformation = XMutualInformation.astype(int)

In [64]:
X = X.astype(int)
X = X.drop(12)

## Melatih Model

### X hasil variance threshold (X)

In [65]:
# memisahkan dataset ke dalam set training dan set testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

In [67]:
X

Alternate_Yes  Bar_Yes  Fri/Sat_Yes  Hungry_Yes  Patrons_None  \
0               1        0            0           1             0   
1               1        0            0           1             0   
2               0        1            0           0             0   
3               1        0            1           1             0   
4               1        0            1           0             0   
5               0        1            0           1             0   
6               0        1            0           0             1   
7               0        0            0           1             0   
8               0        1            1           0             0   
9               1        1            1           1             0   
10              0        0            0           0             1   
11              1        1            1           1             0   

    Patrons_Some  Price_$$  Price_$$$  Rain_Yes  Res_Yes  Type_French  \
0              1         0          1         0        1            1   
1              0         0          0         0        0            0   
2              1         0          0         0        0            0   
3              0         0          0         0        0            0   
4              0         0          1         0        1            1   
5              1         1          0         1        1            0   
6              0         0          0         1        0            0   
7              1         1          0         1        1            0   
8              0         0          0         1        0            0   
9              0         0          1         0        1            0   
10             0         0          0         0        0            0   
11             0         0          0         0        0            0   

    Type_Italian  Type_Thai  Est_10-30  Est_30-60  Est_>60  
0              0          0          0          0        0  
1              0          1          0          1        0  
2              0          0          0          0        0  
3              0          1          1          0        0  
4              0          0          0          0        1  
5              1          0          0          0        0  
6              0          0          0          0        0  
7              0          1          0          0        0  
8              0          0          0          0        1  
9              1          0          1          0        0  
10             0          1          0          0        0  
11             0          0          0          1        0

In [68]:
# melatih model dengan set training
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [69]:
# membuat prediksi hasil set testing
predictions = gnb.predict(X_test)

In [70]:
# membandingkan hasil prediksi dan label sesungguhnya
from sklearn.metrics import classification_report,confusion_matrix

In [71]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          No       0.67      0.67      0.67         3
         Yes       0.50      0.50      0.50         2

    accuracy                           0.60         5
   macro avg       0.58      0.58      0.58         5
weighted avg       0.60      0.60      0.60         5



In [72]:
print(confusion_matrix(y_test,predictions))

[[2 1]
 [1 1]]


### X hasil Mutual Information

In [73]:
# memisahkan dataset ke dalam set training dan set testing
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(XMutualInformation, y, test_size=0.4, random_state=1)

In [74]:
X_train2

Hungry_Yes  Patrons_Some  Type_Thai  Est_>60
6            0             0          0        0
0            1             1          0        0
7            1             1          1        0
11           1             0          0        0
9            1             0          0        0
8            0             0          0        1
5            1             1          0        0

In [75]:
# melatih model dengan set training
from sklearn.naive_bayes import GaussianNB
gnb2 = GaussianNB()
gnb2.fit(X_train2, y_train2)

GaussianNB()

In [76]:
predictions2 = gnb2.predict(X_test2)

In [77]:
print(classification_report(y_test2,predictions2))

              precision    recall  f1-score   support

          No       1.00      0.67      0.80         3
         Yes       0.67      1.00      0.80         2

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5



In [78]:
print(confusion_matrix(y_test2,predictions2))

[[2 1]
 [0 2]]


## Evaluasi Model dengan Repeated 5-fold cross-validation


In [79]:
from numpy import mean
from numpy import std
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

# prepare the cross-validation procedure
cv = RepeatedKFold(n_splits=5, n_repeats=3, random_state=123)

### Evaluasi model gnb (X hasil variance threshold)

In [80]:
scores = cross_val_score(gnb, X, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [81]:
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.533 (0.237)


In [82]:
#evaluasi dengan beberapa parameter

In [83]:
scoring = {'acc': 'accuracy',
           'prec_macro': 'precision_macro',
           'rec_macro': 'recall_macro'}

In [84]:
scores_multi = cross_validate(gnb, X, y, scoring=scoring, cv=cv, n_jobs=-1)

In [85]:
scores_df = pd.DataFrame(scores_multi)

In [86]:
scores_df

fit_time  score_time  test_acc  test_prec_macro  test_rec_macro
0   0.002002    0.002998  1.000000         1.000000            1.00
1   0.005018    0.006996  0.666667         0.750000            0.75
2   0.003009    0.014007  0.500000         0.250000            0.50
3   0.005003    0.012013  0.500000         0.500000            0.25
4   0.005009    0.008991  0.500000         0.500000            0.25
5   0.006012    0.005988  1.000000         1.000000            1.00
6   0.005008    0.004989  0.333333         0.250000            0.25
7   0.003998    0.007988  0.500000         0.500000            0.25
8   0.004009    0.009994  0.500000         0.250000            0.50
9   0.005009    0.007987  0.000000         0.000000            0.00
10  0.004987    0.005995  0.666667         0.750000            0.75
11  0.005002    0.005995  0.333333         0.166667            0.50
12  0.004987    0.006995  0.500000         0.500000            0.25
13  0.005989    0.006992  0.500000         0.500000            0.25
14  0.004995    0.008002  0.500000         0.250000            0.50

In [87]:
scores_df['test_acc'].mean()

0.5333333333333333

In [88]:
scores_df['test_prec_macro'].mean()

0.4777777777777778

In [89]:
scores_df['test_rec_macro'].mean()

0.4666666666666667

### Eval gnb2 (X hasil mutual information)

In [90]:
scores2 = cross_val_score(gnb2, XMutualInformation, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [91]:
print('Accuracy: %.3f (%.3f)' % (mean(scores2), std(scores2)))

Accuracy: 0.711 (0.282)


In [92]:
scores2_multi = cross_validate(gnb2, XMutualInformation, y, scoring=scoring, cv=cv, n_jobs=-1)

In [93]:
scores2_df = pd.DataFrame(scores2_multi)

In [94]:
scores2_df

fit_time  score_time  test_acc  test_prec_macro  test_rec_macro
0   0.005018    0.004999  1.000000         1.000000            1.00
1   0.005019    0.006993  0.666667         0.750000            0.75
2   0.005019    0.008982  0.500000         0.250000            0.50
3   0.004022    0.007992  0.500000         0.500000            0.25
4   0.005017    0.004997  1.000000         1.000000            1.00
5   0.005009    0.005995  1.000000         1.000000            1.00
6   0.007001    0.006998  0.666667         0.333333            0.50
7   0.003003    0.007988  0.500000         0.500000            0.25
8   0.005992    0.004992  1.000000         1.000000            1.00
9   0.004993    0.004998  0.000000         0.000000            0.00
10  0.004992    0.004994  0.666667         0.750000            0.75
11  0.004992    0.004994  0.666667         0.750000            0.75
12  0.003993    0.004998  1.000000         1.000000            1.00
13  0.003993    0.002992  1.000000         1.000000            1.00
14  0.004002    0.005000  0.500000         0.250000            0.50

In [95]:
scores2_df['test_acc'].mean()

0.711111111111111

In [96]:
scores2_df['test_prec_macro'].mean()

0.6722222222222222

In [97]:
scores2_df['test_rec_macro'].mean()

0.6833333333333333