# Praktikum 5 - Naive Bayes dengan Preprocessing dan K-Cross Validation

# Naive Bayes Classifier

In [1]:
import numpy as np
import pandas as pd
from IPython import display

## Data

In [2]:
from sklearn import datasets

In [3]:
data=datasets.fetch_covtype(data_home=None, download_if_missing=True, random_state=None, shuffle=False, return_X_y=False)

In [4]:
data.target

array([5, 5, 2, ..., 3, 3, 3], dtype=int32)

In [5]:
data.DESCR

".. _covtype_dataset:\n\nForest covertypes\n-----------------\n\nThe samples in this dataset correspond to 30×30m patches of forest in the US,\ncollected for the task of predicting each patch's cover type,\ni.e. the dominant species of tree.\nThere are seven covertypes, making this a multiclass classification problem.\nEach sample has 54 features, described on the\n`dataset's homepage <https://archive.ics.uci.edu/ml/datasets/Covertype>`__.\nSome of the features are boolean indicators,\nwhile others are discrete or continuous measurements.\n\n**Data Set Characteristics:**\n\n    =================   ============\n    Classes                        7\n    Samples total             581012\n    Dimensionality                54\n    Features                     int\n    =================   ============\n\n:func:`sklearn.datasets.fetch_covtype` will load the covertype dataset;\nit returns a dictionary-like 'Bunch' object\nwith the feature matrix in the ``data`` member\nand the target values i

In [6]:
X = pd.DataFrame(data.data)

In [7]:
y = pd.DataFrame(data.target)

In [8]:
df=pd.concat([X,y],axis=1)

In [9]:
df.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
30    float64
31    float64
32    float64
33    float64
34    float64
35    float64
36    float64
37    float64
38    float64
39    float64
40    float64
41    float64
42    float64
43    float64
44    float64
45    float64
46    float64
47    float64
48    float64
49    float64
50    float64
51    float64
52    float64
53    float64
0       int32
dtype: object

## Preprocessing

### Feature Selection

### Feature Selection : by Variance Threshold

<a><img src="https://cdn1.byjus.com/wp-content/uploads/2021/03/variance-and-sd-formula.png"/></a>

<a><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNy_TQDpkMzCmytuj1Ncr_GcYLu7pZkpH2cw&usqp=CAU"></a>

In [10]:
from sklearn.feature_selection import VarianceThreshold

In [11]:
selector = VarianceThreshold()

In [12]:
XVarianceThreshold = selector.fit_transform(X)

In [13]:
XVarianceThreshold.shape

(581012, 54)

### Feature Selection : by Mutual Infomation/Information Gain

<a><img src="https://miro.medium.com/max/1400/1*sHASwCjxy-Tsr3eaDTeHXw.png"></a>

In [14]:
from sklearn.feature_selection import mutual_info_classif
import time

In [15]:
y = data.target

In [17]:
start = time.time()
XMutualInformationValue = mutual_info_classif(X,y)
end = time.time()
print(end - start)

90.24970483779907


In [18]:
XMutualInformationValue

array([4.57797232e-01, 1.97139126e-02, 3.83884135e-02, 2.54516895e-02,
       1.77768108e-02, 8.97561496e-02, 3.09637417e-02, 2.19022300e-02,
       2.03470425e-02, 7.06291205e-02, 7.91192984e-02, 1.32516314e-02,
       1.64389203e-02, 1.46822948e-01, 1.13768823e-02, 2.43685434e-02,
       1.40225330e-02, 2.89112499e-02, 7.09415541e-03, 2.01679282e-02,
       8.98304471e-04, 3.58939986e-04, 2.24769994e-03, 6.54482352e-02,
       8.54121218e-03, 2.57380422e-02, 1.01443083e-02, 1.93785683e-03,
       0.00000000e+00, 1.66139587e-03, 6.04294055e-03, 2.37579183e-03,
       2.69204282e-03, 2.27842657e-03, 5.28453824e-04, 2.33620459e-02,
       2.13330059e-02, 4.60574974e-03, 0.00000000e+00, 1.17017568e-03,
       1.05176828e-03, 5.49304250e-04, 3.43270024e-02, 1.24308402e-02,
       4.49686871e-03, 9.69655518e-03, 6.80449078e-03, 7.77591061e-04,
       4.06041475e-03, 9.55226888e-05, 9.54482627e-04, 3.05490527e-02,
       2.85677937e-02, 1.77805831e-02])

In [19]:
XMutualInformation=X.copy()

In [20]:
XMutualInformation

0      1     2      3      4       5      6      7      8   \
0       2596.0   51.0   3.0  258.0    0.0   510.0  221.0  232.0  148.0   
1       2590.0   56.0   2.0  212.0   -6.0   390.0  220.0  235.0  151.0   
2       2804.0  139.0   9.0  268.0   65.0  3180.0  234.0  238.0  135.0   
3       2785.0  155.0  18.0  242.0  118.0  3090.0  238.0  238.0  122.0   
4       2595.0   45.0   2.0  153.0   -1.0   391.0  220.0  234.0  150.0   
...        ...    ...   ...    ...    ...     ...    ...    ...    ...   
581007  2396.0  153.0  20.0   85.0   17.0   108.0  240.0  237.0  118.0   
581008  2391.0  152.0  19.0   67.0   12.0    95.0  240.0  237.0  119.0   
581009  2386.0  159.0  17.0   60.0    7.0    90.0  236.0  241.0  130.0   
581010  2384.0  170.0  15.0   60.0    5.0    90.0  230.0  245.0  143.0   
581011  2383.0  165.0  13.0   60.0    4.0    67.0  231.0  244.0  141.0   

            9   ...   44   45   46   47   48   49   50   51   52   53  
0       6279.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1       6225.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2       6121.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3       6211.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4       6172.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
581007   837.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581008   845.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581009   854.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581010   864.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581011   875.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[581012 rows x 54 columns]

In [21]:
XMutualInformation.loc[581012+1]=XMutualInformationValue

In [22]:
XMutualInformation

0           1          2           3           4   \
0       2596.000000   51.000000   3.000000  258.000000    0.000000   
1       2590.000000   56.000000   2.000000  212.000000   -6.000000   
2       2804.000000  139.000000   9.000000  268.000000   65.000000   
3       2785.000000  155.000000  18.000000  242.000000  118.000000   
4       2595.000000   45.000000   2.000000  153.000000   -1.000000   
...             ...         ...        ...         ...         ...   
581008  2391.000000  152.000000  19.000000   67.000000   12.000000   
581009  2386.000000  159.000000  17.000000   60.000000    7.000000   
581010  2384.000000  170.000000  15.000000   60.000000    5.000000   
581011  2383.000000  165.000000  13.000000   60.000000    4.000000   
581013     0.457797    0.019714   0.038388    0.025452    0.017777   

                 5           6           7           8            9   ...  \
0        510.000000  221.000000  232.000000  148.000000  6279.000000  ...   
1        390.000000  220.000000  235.000000  151.000000  6225.000000  ...   
2       3180.000000  234.000000  238.000000  135.000000  6121.000000  ...   
3       3090.000000  238.000000  238.000000  122.000000  6211.000000  ...   
4        391.000000  220.000000  234.000000  150.000000  6172.000000  ...   
...             ...         ...         ...         ...          ...  ...   
581008    95.000000  240.000000  237.000000  119.000000   845.000000  ...   
581009    90.000000  236.000000  241.000000  130.000000   854.000000  ...   
581010    90.000000  230.000000  245.000000  143.000000   864.000000  ...   
581011    67.000000  231.000000  244.000000  141.000000   875.000000  ...   
581013     0.089756    0.030964    0.021902    0.020347     0.070629  ...   

              44        45        46        47       48        49        50  \
0       0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
1       0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
2       0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
3       0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
4       0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
...          ...       ...       ...       ...      ...       ...       ...   
581008  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
581009  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
581010  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
581011  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
581013  0.004497  0.009697  0.006804  0.000778  0.00406  0.000096  0.000954   

              51        52        53  
0       0.000000  0.000000  0.000000  
1       0.000000  0.000000  0.000000  
2       0.000000  0.000000  0.000000  
3       0.000000  0.000000  0.000000  
4       0.000000  0.000000  0.000000  
...          ...       ...       ...  
581008  0.000000  0.000000  0.000000  
581009  0.000000  0.000000  0.000000  
581010  0.000000  0.000000  0.000000  
581011  0.000000  0.000000  0.000000  
581013  0.030549  0.028568  0.017781  

[581013 rows x 54 columns]

In [23]:
XMutualInformation = XMutualInformation.drop([col for col in XMutualInformation.columns if XMutualInformation[col][581013]==0.0], axis=1)


In [24]:
XMutualInformation = XMutualInformation.drop(581013)

In [25]:
XMutualInformation = XMutualInformation.astype(int)

## Melatih Model

### X hasil variance threshold (X)

In [26]:
# memisahkan dataset ke dalam set training dan set testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

In [27]:
X

0      1     2      3      4       5      6      7      8   \
0       2596.0   51.0   3.0  258.0    0.0   510.0  221.0  232.0  148.0   
1       2590.0   56.0   2.0  212.0   -6.0   390.0  220.0  235.0  151.0   
2       2804.0  139.0   9.0  268.0   65.0  3180.0  234.0  238.0  135.0   
3       2785.0  155.0  18.0  242.0  118.0  3090.0  238.0  238.0  122.0   
4       2595.0   45.0   2.0  153.0   -1.0   391.0  220.0  234.0  150.0   
...        ...    ...   ...    ...    ...     ...    ...    ...    ...   
581007  2396.0  153.0  20.0   85.0   17.0   108.0  240.0  237.0  118.0   
581008  2391.0  152.0  19.0   67.0   12.0    95.0  240.0  237.0  119.0   
581009  2386.0  159.0  17.0   60.0    7.0    90.0  236.0  241.0  130.0   
581010  2384.0  170.0  15.0   60.0    5.0    90.0  230.0  245.0  143.0   
581011  2383.0  165.0  13.0   60.0    4.0    67.0  231.0  244.0  141.0   

            9   ...   44   45   46   47   48   49   50   51   52   53  
0       6279.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1       6225.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2       6121.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3       6211.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4       6172.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
581007   837.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581008   845.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581009   854.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581010   864.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
581011   875.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[581012 rows x 54 columns]

In [28]:
# melatih model dengan set training
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [29]:
# membuat prediksi hasil set testing
predictions = gnb.predict(X_test)

In [30]:
# membandingkan hasil prediksi dan label sesungguhnya
from sklearn.metrics import classification_report,confusion_matrix

In [31]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.50      0.78      0.61     84776
           2       0.84      0.16      0.27    113349
           3       0.44      0.81      0.57     14333
           4       0.22      0.83      0.35      1077
           5       0.08      0.63      0.14      3762
           6       0.38      0.08      0.14      6943
           7       0.37      0.81      0.51      8165

    accuracy                           0.46    232405
   macro avg       0.40      0.59      0.37    232405
weighted avg       0.65      0.46      0.41    232405



In [32]:
print(confusion_matrix(y_test,predictions))

[[66137  3237   494     0  4645   215 10048]
 [63364 17832  8086    94 22111   627  1235]
 [   30     9 11608  2408   208    70     0]
 [    0     0   183   894     0     0     0]
 [  716    69   556     0  2387    34     0]
 [  154    18  5179   648   370   574     0]
 [ 1423    49    37     0    56     0  6600]]


### X hasil Mutual Information

In [33]:
# memisahkan dataset ke dalam set training dan set testing
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(XMutualInformation, y, test_size=0.4, random_state=1)

In [34]:
X_train2

0    1   2    3   4     5    6    7    8     9   ...  44  45  46  \
562432  2563   77  14   90  44  1519  237  212  103  1789  ...   0   0   0   
569390  2790  212  24   42  13  3171  192  254  187  1492  ...   0   0   0   
485820  3138  269  16  255  59  3197  175  244  207  1621  ...   1   0   0   
426800  2816   61  12  277  81  1273  230  214  115  2728  ...   0   0   0   
370460  2766   27  13  201  19  2910  214  212  131   663  ...   0   0   0   
...      ...  ...  ..  ...  ..   ...  ...  ...  ...   ...  ...  ..  ..  ..   
371403  3288  353  13  417  77  3439  196  216  157  2698  ...   1   0   0   
491263  3075  140  14  240  -6   866  240  235  122  1237  ...   0   0   0   
470924  3095   84   7    0   0  1167  230  228  131  2140  ...   0   0   0   
491755  2889   64   9  218  84   685  229  221  125   930  ...   0   0   1   
128037  2771   27  11    0   0  1880  215  217  137  2089  ...   0   0   0   

        47  48  49  50  51  52  53  
562432   0   0   0   0   0   0   0  
569390   0   0   0   0   0   0   0  
485820   0   0   0   0   0   0   0  
426800   0   0   0   0   0   0   0  
370460   0   0   0   0   0   0   0  
...     ..  ..  ..  ..  ..  ..  ..  
371403   0   0   0   0   0   0   0  
491263   0   0   0   0   0   0   0  
470924   0   0   0   0   0   0   0  
491755   0   0   0   0   0   0   0  
128037   0   0   0   0   0   0   0  

[348607 rows x 52 columns]

In [35]:
# melatih model dengan set training
from sklearn.naive_bayes import GaussianNB
gnb2 = GaussianNB()
gnb2.fit(X_train2, y_train2)

GaussianNB()

In [36]:
predictions2 = gnb2.predict(X_test2)

In [37]:
print(classification_report(y_test2,predictions2))

              precision    recall  f1-score   support

           1       0.50      0.78      0.61     84776
           2       0.84      0.16      0.27    113349
           3       0.44      0.81      0.57     14333
           4       0.22      0.83      0.35      1077
           5       0.08      0.63      0.14      3762
           6       0.38      0.08      0.13      6943
           7       0.37      0.81      0.50      8165

    accuracy                           0.46    232405
   macro avg       0.40      0.59      0.37    232405
weighted avg       0.65      0.46      0.41    232405



In [38]:
print(confusion_matrix(y_test2,predictions2))

[[66244  3282   494     0  4515   212 10029]
 [63505 18040  8084    94 21639   629  1358]
 [   29    10 11608  2408   207    71     0]
 [    0     0   183   894     0     0     0]
 [  721    69   556     0  2382    34     0]
 [  145    31  5179   649   368   571     0]
 [ 1428    50    37     0    55     0  6595]]


## Evaluasi Model dengan Repeated 5-fold cross-validation


In [39]:
from numpy import mean
from numpy import std
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

# prepare the cross-validation procedure
cv = RepeatedKFold(n_splits=5, n_repeats=3, random_state=123)

### Evaluasi model gnb (X hasil variance threshold)

In [40]:
scores = cross_val_score(gnb, X, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [41]:
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.459 (0.001)


In [42]:
#evaluasi dengan beberapa parameter

In [43]:
scoring = {'acc': 'accuracy',
           'prec_macro': 'precision_macro',
           'rec_macro': 'recall_macro'}

In [44]:
scores_multi = cross_validate(gnb, X, y, scoring=scoring, cv=cv, n_jobs=-1)

In [45]:
scores_df = pd.DataFrame(scores_multi)

In [46]:
scores_df

fit_time  score_time  test_acc  test_prec_macro  test_rec_macro
0   6.806998    0.845076  0.458379         0.408380        0.577344
1   6.650677    0.721510  0.458499         0.407444        0.590951
2   7.800397    0.889149  0.461076         0.406171        0.588560
3   6.632140    0.656259  0.457651         0.402749        0.587749
4   7.330962    0.890562  0.459648         0.407692        0.593908
5   6.948525    0.764780  0.461365         0.407234        0.586449
6   7.751572    0.786914  0.457587         0.407894        0.588725
7   7.555551    0.705156  0.457996         0.399934        0.589046
8   4.005535    0.785025  0.460293         0.409983        0.586078
9   3.051013    0.757417  0.458150         0.405877        0.588126
10  3.751384    0.752983  0.460160         0.402180        0.582788
11  3.980708    0.712694  0.459162         0.406378        0.585788
12  4.673755    0.424142  0.459656         0.407016        0.587824
13  4.219227    0.496118  0.457849         0.408646        0.590250
14  4.587277    0.301209  0.458340         0.407881        0.589828

In [47]:
scores_df['test_acc'].mean()

0.45905420150392084

In [48]:
scores_df['test_prec_macro'].mean()

0.406363869428835

In [49]:
scores_df['test_rec_macro'].mean()

0.5875607200178679

### Eval gnb2 (X hasil mutual information)

In [50]:
scores2 = cross_val_score(gnb2, XMutualInformation, y, scoring='accuracy', cv=cv, n_jobs=-1)

In [51]:
print('Accuracy: %.3f (%.3f)' % (mean(scores2), std(scores2)))

Accuracy: 0.460 (0.001)


In [52]:
scores2_multi = cross_validate(gnb2, XMutualInformation, y, scoring=scoring, cv=cv, n_jobs=-1)

In [53]:
scores2_df = pd.DataFrame(scores2_multi)

In [54]:
scores2_df

fit_time  score_time  test_acc  test_prec_macro  test_rec_macro
0   5.019133    0.852479  0.459954         0.408407        0.577672
1   4.935774    0.970582  0.459825         0.407157        0.590377
2   4.777848    0.988589  0.462557         0.406241        0.588524
3   4.918181    0.817271  0.459200         0.402847        0.587706
4   4.725909    0.983513  0.461008         0.407223        0.593641
5   4.527294    0.564685  0.462716         0.406754        0.585717
6   4.583265    0.780402  0.458904         0.407292        0.588607
7   4.614972    0.716087  0.459252         0.400209        0.588924
8   1.159788    0.863707  0.461808         0.410363        0.586061
9   1.373743    1.204116  0.459725         0.406240        0.588256
10  3.914774    0.752706  0.461606         0.401966        0.582621
11  4.037065    0.762173  0.460496         0.405777        0.585384
12  3.910658    0.646446  0.460904         0.406919        0.587421
13  4.009372    0.712101  0.459433         0.408597        0.590180
14  4.044185    0.576427  0.459519         0.407702        0.589387

In [55]:
scores2_df['test_acc'].mean()

0.4604603687256778

In [56]:
scores2_df['test_prec_macro'].mean()

0.40624628795854373

In [57]:
scores2_df['test_rec_macro'].mean()

0.5873651146663018