In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load datasets package from scikit-learn
from sklearn import datasets

In [3]:
data = datasets.load_wine()
df = pd.DataFrame(data.data, columns = data.feature_names)

In [4]:
print(data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])


In [5]:
print(data.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [6]:
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [7]:
df.isna().any()

alcohol                         False
malic_acid                      False
ash                             False
alcalinity_of_ash               False
magnesium                       False
total_phenols                   False
flavanoids                      False
nonflavanoid_phenols            False
proanthocyanins                 False
color_intensity                 False
hue                             False
od280/od315_of_diluted_wines    False
proline                         False
dtype: bool

In [9]:
y = data.target

# One-Hot Encoding

In [8]:
X_enc = pd.get_dummies(df)

In [10]:
X_enc.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [11]:
X = X_enc

In [12]:
X

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [13]:
X_enc = X_enc.drop(['nonflavanoid_phenols'], axis = 1)

In [14]:
X_enc.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'proanthocyanins', 'color_intensity',
       'hue', 'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [15]:
X = X_enc

In [16]:
X

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  proanthocyanins  color_intensity   hue  \
0          3.06             2.29             5.64  1.04   
1          2.76             1.28             4.38  1.05   
2          3.24             2.81             5.68  1.03   
3          3.49             2.18             7.80  0.86   
4          2.69             1.82             4.32  1.04   
..          ...              ...              ...   ...   
173        0.61             1.06             7.70  0.64   
174        0.75             1.41             7.30  0.70   
175        0.69             1.35            10.20  0.59   
176        0.68             1.46             9.30  0.60   
177        0.76             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 12 columns]

# Feature Selection: by Variance Threshold

In [17]:
from sklearn.feature_selection import VarianceThreshold

In [18]:
selector = VarianceThreshold()

In [19]:
XVarianceThreshold = selector.fit_transform(X)

In [20]:
XVarianceThreshold.shape

(178, 12)

# Feature Selection: by Mutual Information/Information Gain

In [21]:
from sklearn.feature_selection import mutual_info_classif

In [22]:
XMutualInformationValue = mutual_info_classif(X, y)

In [23]:
XMutualInformationValue

array([0.46752372, 0.27952657, 0.07538725, 0.26802905, 0.22556911,
       0.41100219, 0.66745884, 0.28687485, 0.5477588 , 0.44055947,
       0.49793212, 0.56242796])

In [24]:
XMutualInformation = X

In [25]:
XMutualInformation

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  proanthocyanins  color_intensity   hue  \
0          3.06             2.29             5.64  1.04   
1          2.76             1.28             4.38  1.05   
2          3.24             2.81             5.68  1.03   
3          3.49             2.18             7.80  0.86   
4          2.69             1.82             4.32  1.04   
..          ...              ...              ...   ...   
173        0.61             1.06             7.70  0.64   
174        0.75             1.41             7.30  0.70   
175        0.69             1.35            10.20  0.59   
176        0.68             1.46             9.30  0.60   
177        0.76             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 12 columns]

In [26]:
XMutualInformation.loc[178] = XMutualInformationValue

In [29]:
XMutualInformation = XMutualInformation.drop([col for col in X.columns if X[col][178] == 0], axis = 1)

In [30]:
XMutualInformation = XMutualInformation.drop(178)

In [31]:
XMutualInformation = XMutualInformation.replace(to_replace = [0.0], value = 0)
XMutualInformation = XMutualInformation.replace(to_replace = [1.0], value = 1)

In [32]:
XMutualInformation = XMutualInformation.astype(int)

In [33]:
X = X.astype(int)
X = X.drop(178)

In [34]:
X

alcohol  malic_acid  ash  alcalinity_of_ash  magnesium  total_phenols  \
0         14           1    2                 15        127              2   
1         13           1    2                 11        100              2   
2         13           2    2                 18        101              2   
3         14           1    2                 16        113              3   
4         13           2    2                 21        118              2   
..       ...         ...  ...                ...        ...            ...   
173       13           5    2                 20         95              1   
174       13           3    2                 23        102              1   
175       13           4    2                 20        120              1   
176       13           2    2                 20        120              1   
177       14           4    2                 24         96              2   

     flavanoids  proanthocyanins  color_intensity  hue  \
0             3                2                5    1   
1             2                1                4    1   
2             3                2                5    1   
3             3                2                7    0   
4             2                1                4    1   
..          ...              ...              ...  ...   
173           0                1                7    0   
174           0                1                7    0   
175           0                1               10    0   
176           0                1                9    0   
177           0                1                9    0   

     od280/od315_of_diluted_wines  proline  
0                               3     1065  
1                               3     1050  
2                               3     1185  
3                               3     1480  
4                               2      735  
..                            ...      ...  
173                             1      740  
174                             1      750  
175                             1      835  
176                             1      840  
177                             1      560  

[178 rows x 12 columns]

# X hasil variance threshold (X)

In [35]:
# Memisahkan dataset ke dalam set training dan set testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size = 0.4, random_state = 1)

In [36]:
X

alcohol  malic_acid  ash  alcalinity_of_ash  magnesium  total_phenols  \
0         14           1    2                 15        127              2   
1         13           1    2                 11        100              2   
2         13           2    2                 18        101              2   
3         14           1    2                 16        113              3   
4         13           2    2                 21        118              2   
..       ...         ...  ...                ...        ...            ...   
173       13           5    2                 20         95              1   
174       13           3    2                 23        102              1   
175       13           4    2                 20        120              1   
176       13           2    2                 20        120              1   
177       14           4    2                 24         96              2   

     flavanoids  proanthocyanins  color_intensity  hue  \
0             3                2                5    1   
1             2                1                4    1   
2             3                2                5    1   
3             3                2                7    0   
4             2                1                4    1   
..          ...              ...              ...  ...   
173           0                1                7    0   
174           0                1                7    0   
175           0                1               10    0   
176           0                1                9    0   
177           0                1                9    0   

     od280/od315_of_diluted_wines  proline  
0                               3     1065  
1                               3     1050  
2                               3     1185  
3                               3     1480  
4                               2      735  
..                            ...      ...  
173                             1      740  
174                             1      750  
175                             1      835  
176                             1      840  
177                             1      560  

[178 rows x 12 columns]

In [37]:
# Melatih model dengan set training
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [38]:
# Membuat prediksi hasil set training
predictions = gnb.predict(X_test)

In [39]:
# Membandingkan hasil prediksi dan label sesungguhnya
from sklearn.metrics import classification_report, confusion_matrix

In [40]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98        28
           1       1.00      0.96      0.98        27
           2       1.00      1.00      1.00        17

    accuracy                           0.99        72
   macro avg       0.99      0.99      0.99        72
weighted avg       0.99      0.99      0.99        72



In [41]:
print(confusion_matrix(y_test, predictions))

[[28  0  0]
 [ 1 26  0]
 [ 0  0 17]]


# X hasil Mutual Information

In [44]:
# Memisahkan dataset ke dalam set training dan set testing
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(XMutualInformation, y, test_size = 0.4, random_state = 1)

In [45]:
X_train2

alcohol  malic_acid  ash  alcalinity_of_ash  magnesium  total_phenols  \
168       13           2    2                 24        105              1   
175       13           4    2                 20        120              1   
118       12           3    1                 16         80              1   
75        11           1    1                 16         97              1   
21        12           3    2                 18        102              2   
..       ...         ...  ...                ...        ...            ...   
133       12           3    2                 21        106              1   
137       12           5    2                 25         96              1   
72        13           1    2                 24         87              1   
140       12           2    2                 21         96              1   
37        13           1    2                 18         98              2   

     flavanoids  proanthocyanins  color_intensity  hue  \
168           0                1                8    0   
175           0                1               10    0   
118           1                0                3    0   
75            1                1                3    1   
21            2                1                4    1   
..          ...              ...              ...  ...   
133           1                0                5    0   
137           0                1                5    0   
72            1                1                3    0   
140           0                0                4    0   
37            2                1                4    1   

     od280/od315_of_diluted_wines  proline  
168                             1      750  
175                             1      835  
118                             2      372  
75                              2      428  
21                              3      770  
..                            ...      ...  
133                             1      600  
137                             1      515  
72                              2      472  
140                             2      600  
37                              2     1105  

[106 rows x 12 columns]

In [47]:
# Melatih model dengan set training
from sklearn.naive_bayes import GaussianNB
gnb2 = GaussianNB()
gnb2.fit(X_train2, y_train2)

GaussianNB()

In [48]:
predictions2 = gnb2.predict(X_test2)

In [49]:
print(classification_report(y_test2, predictions2))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        28
           1       1.00      0.89      0.94        27
           2       0.94      1.00      0.97        17

    accuracy                           0.96        72
   macro avg       0.96      0.96      0.96        72
weighted avg       0.96      0.96      0.96        72



In [50]:
print(confusion_matrix(y_test2, predictions2))

[[28  0  0]
 [ 2 24  1]
 [ 0  0 17]]


# Evaluasi Model dengan Repeated 5-fold cross-validation

In [51]:
from numpy import mean
from numpy import std
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

# prepare the cross-validation procedure
cv = RepeatedKFold(n_splits = 5, n_repeats = 3, random_state = 123)

# Evaluasi model gnb (X hasil variance threshold)

In [52]:
scores = cross_val_score(gnb, X, y, scoring = 'accuracy', cv = cv, n_jobs = -1)

In [53]:
# Report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.936 (0.038)


In [54]:
scoring = {'acc': 'accuracy', 'prec_macro': 'precision_macro', 'rec_macro': 'recall_macro'}

In [55]:
scores_multi = cross_validate(gnb, df, y, scoring = scoring, cv = cv, n_jobs = -1)

In [56]:
scores_df = pd.DataFrame(scores_multi)

In [57]:
scores_df

fit_time  score_time  test_acc  test_prec_macro  test_rec_macro
0   0.018047    0.007826  1.000000         1.000000        1.000000
1   0.012336    0.011575  1.000000         1.000000        1.000000
2   0.017714    0.010367  1.000000         1.000000        1.000000
3   0.023361    0.020568  0.914286         0.918519        0.924908
4   0.031325    0.005978  0.971429         0.962963        0.982456
5   0.022838    0.019154  0.972222         0.976190        0.977778
6   0.034702    0.010678  0.944444         0.932660        0.962963
7   0.014449    0.006749  1.000000         1.000000        1.000000
8   0.007877    0.002621  0.942857         0.952381        0.952381
9   0.001589    0.001708  0.971429         0.977778        0.958333
10  0.001302    0.001000  1.000000         1.000000        1.000000
11  0.001027    0.000968  0.944444         0.944444        0.950000
12  0.001450    0.000982  1.000000         1.000000        1.000000
13  0.007838    0.003267  0.971429         0.977778        0.974359
14  0.001652    0.001669  0.971429         0.969697        0.976190

In [58]:
scores_df['test_acc'].mean()

0.9735978835978837

In [59]:
scores_df['test_prec_macro'].mean()

0.9741606541606541

In [60]:
scores_df['test_rec_macro'].mean()

0.9772912694842518

# Eval gnb2 (X hasil mutual information)

In [61]:
scores2 = cross_val_score(gnb2, XMutualInformation, y, scoring = 'accuracy', cv = cv, n_jobs = -1)

In [62]:
print('Accuracy: %.3f (%.3f)' % (mean(scores2), std(scores2)))

Accuracy: 0.936 (0.038)


In [63]:
scores2_multi = cross_validate(gnb2, XMutualInformation, y, scoring = scoring, cv = cv, n_jobs = -1)

In [64]:
scores2_df = pd.DataFrame(scores2_multi)

In [65]:
scores2_df

fit_time  score_time  test_acc  test_prec_macro  test_rec_macro
0   0.005496    0.003417  0.972222         0.981481        0.969697
1   0.008729    0.002048  0.972222         0.958333        0.974359
2   0.011333    0.008477  0.888889         0.881313        0.904762
3   0.008792    0.005602  0.942857         0.939153        0.950549
4   0.013824    0.006669  0.914286         0.909091        0.947368
5   0.001451    0.001819  0.972222         0.962963        0.974359
6   0.003086    0.003386  0.888889         0.878788        0.925926
7   0.019282    0.004350  0.972222         0.958333        0.972222
8   0.002874    0.002153  0.885714         0.905556        0.891534
9   0.001612    0.002338  0.971429         0.977778        0.958333
10  0.002077    0.001047  0.944444         0.955556        0.925926
11  0.007593    0.001527  0.972222         0.966667        0.977778
12  0.012893    0.007115  0.944444         0.933333        0.964912
13  0.002431    0.002463  0.942857         0.939153        0.950549
14  0.003433    0.002264  0.857143         0.862471        0.874459

In [66]:
scores2_df['test_acc'].mean()

0.9361375661375662

In [67]:
scores2_df['test_prec_macro'].mean()

0.9339979773313107

In [68]:
scores2_df['test_rec_macro'].mean()

0.9441823251472374